### ISSUE TITLE
/dev/vcsm is removed from kernel >= 5.9

### ISSUE THREAD

**Issue by ny-a** [Idein/rpi-vcsm#2] opened 2021-05-27 11:00 UTC
I found `/dev/vcsm` is missing in latest Raspberry Pi OS Lite image (downloaded from [official site](https://www.raspberrypi.org/software/operating-systems/), released at March 4th 2021, kernel version is 5.10).

According to 6th comment in https://github.com/raspberrypi/linux/issues/4167, vcsm got removed from 5.9.y and later.

So I downgraded kernel to 5.4.83 by runnning `sudo rpi-update 43022f5adbbf5d6e05ea0e022a3090c2c9feff7c` (which is the previous firmware commit of kernel 5.10.0: https://github.com/Hexxeh/rpi-firmware/commit/7378e549a785bd486c19dc2ed737ca4a1e983351) to use vcsm.

I think adding available kernel version in README is helpful for other user.

Thanks.

**Comment by Terminus-IMRC** [comment] 2021-05-27 13:31
Thank you for the report, we didn't notice that because we are still fixed to 4.19 in our product!
Yes, I think the workaround is to use the old kernels <= 5.9.
We are going to add a note on this issue and develop a library for using vc_sm_cma instead of vc_sm.
We'll notify you here when it's done.

**Comment by Terminus-IMRC** [comment] 2021-06-06 00:09
The issue is now resolved via #3, be sure to use the new 3.0.0 version instead of 2.0.0.
Because the API is slightly modified, a fix for py-videocore has been proposed: nineties/py-videocore#54.
Thank you again for the interest and the report!

**Closed as completed by Terminus-IMRC** 2021-06-06 00:09 UTC

**Comment by ny-a** [comment] 2021-06-06 06:33
Thank you very much! :tada:
